### ISSUE TITLE
reviews

### ISSUE THREAD

**Issue by ale-strada** [RichardIrala/mascotas-perdidas-webapp-m7#2]
Hola @RichardIrala, como va? la app quedo muy buena, Felicitaciones!! solo tengo 2 observaciones para comentar. Por un lado, no vi como hacer para editar las mascotas publicadas. Y por otro lado, publique 3 mascotas y el mapa solo me mostraba marcada una.
![captura publicadas](https://user-images.githubusercontent.com/79310707/186164500-5f28e691-f08f-42a2-a4b6-f2cc4f72afe7.png)
![captura mascotas](https://user-images.githubusercontent.com/79310707/186164517-5b1af77e-2128-428d-bec1-666e7f7efb6f.png)

**Comment by RichardIrala** [comment]
Buenas ale, publicaste todas en el mismo punto geográfico? si es así posiblemente estén 1 arriba de la otra exactamente en la misma posición por ende no es distinguible si están los 3. Pero si haces scroll hacia abajo te van a aparecer las 3 como cards/cartas. Quizá el problema en el mapa es ese (Están literalmente  ubicadas en el mismo espacio, por ende ese punto solitario en realidad son 3 mascotas en un mismo lugar)

**Comment by RichardIrala** [comment]
Respecto a la funcionalidad de modificar una mascota, ahora comienzo a crearla. Gracias por comentar.

**Comment by ale-strada** [comment]
Dale!! yo no le puse "necesita ajustes" asiq avisame cuando puedas terminar eso asi lo veo de nuevo.

**Comment by RichardIrala** [comment]
Funcionalidad agregada:
![image](https://user-images.githubusercontent.com/93644394/186259148-c07c1d15-6dee-421a-9e3f-96b3e9b8ecd1.png)

**Comment by ale-strada** [comment]
@RichardIrala como va? probe la funcion que agregaste y lo demas. Funciona todo muy bien. Felicitaciones!! Una opinion nomas, para cuando hagas de nuevo el front, estaria bueno tambien poder modificar el nombre y la foto de la mascota. Ademas, que se pueda poner la ubicacion de una forma mas comoda, poner a mano latitud y longitud es un poco dificil.

**Comment by RichardIrala** [comment]
Joya, sisi ando a la espera de que me aprueben. Lo del nombre no lo puse porque me parecía raro cambiarle el nombre. Lo de la imagen lo puedo considerar. Son funcionalidades que le puedo dar ahora cuando me aprueben porque al proyecto lo voy a ir mejorando posteriormente a ello. Buenísimo feedback ale. Y por el tema de colocar la ubicación voy a pensar en alguna solución más didáctica para que se puedan obtener esos datos.

**Comment by ale-strada** [comment]
Yo por mi parte, en reviews ya lo aprobe. Te sugeria lo del nombre xq puede que algun usuario escriba mal y despues quiera cambiarlo, no es tanto agregar solo un campo mas. Y lo de la ubicacion, yo lo resolvi poniendo el mapa en el formulario, entonces al hacer click en algun lugar se guarda esa ubicacion. Esa funcion viene con el mapbox.

**Comment by RichardIrala** [comment]
Tremendo, voy a hacerlo posiblemente posterior a que me aprueben tanto lo del mapa para ayudar al usuario, como también poder cambiarle la foto y que sea algo opcional para el mismo, gracias por el feedback. Recién vi tu desafío y esta espectacular la interfaz

**Comment by ale-strada** [comment]
Gracias Richard!! a seguir con toda!!💪💪 esas mejoras podes hacerlas directamente en el desafio del modulo 8.
