### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by DenisMPar** [RichardIrala/mascotas-perdidas-webapp-m7#3]
Hola Richard esta muy buena la app, pero hay cosas que arreglar:
-  Si reporto una mascota me la muestra en el mapa pero no tengo forma de enviar el reporte como vista, toco en el marcador y no pasa nada

![Screenshot_32](https://user-images.githubusercontent.com/80976314/187432698-b3f9e403-5192-433c-8df0-fcaea2287e06.png)

- Si modifico la ubicación de la mascota ya no se muestra el marcador en el mapa

![Screenshot_1](https://user-images.githubusercontent.com/80976314/187433346-8efc5e8a-0b7c-4f38-a451-8897159613a6.png)
- En la sección de editar, no tengo la opción de modificar foto y tampoco el botón de despublicar.

![Screenshot_2](https://user-images.githubusercontent.com/80976314/187433869-bab48987-b581-469f-89df-d8888aad0d31.png)

- Y por ultimo en la parte de mis datos no tengo un campo para modificar el nombre, o el email en su defecto

![Screenshot_3](https://user-images.githubusercontent.com/80976314/187434135-6c85ebf0-04ff-440b-89e3-0bf125d08a93.png)

Arreglate esas custiones y cualquier cosita estamos por discord.
Saludos!

**Comment by RichardIrala** [comment]
Ah. disculpa son cosas que no quería que cambien y/o en caso del mapa es solo para darse la idea de que hay mascotas cerca pero las opciones se encuentran más abajo. La del nombre me la plantearon un par de personas así que de una, la voy a poner. Y la opción de borrar la foto de perfil me gusto, la voy a poner. Lo de clickear los puntos en el mapa y que lleven a mascotas no esta en mis planes por el momento porque el mapa es solo orientativo. Pero por lo demás en el día lo agrego todo
