### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by amunozdev** [RichardIrala/mascotas-perdidas-webapp-m7#4]
Buenas Richard, lo veo genial, se ve que le metiste muchas ganas y tiempo!

Además de las mejoras sobre la funcionalidad para editar una mascota, estaría muy bueno que puedas mantener la sesión abierta haciendo uso del localStorage y que se pueda cerrar sesión cuando se desee, ya que es algo relativamente fácil de implementar y más cómodo para el usuario que usa la app.

Sumando esas cosas, a mi criterio, ya estaría para aprobar.

**Comment by RichardIrala** [comment]
Funcionalidades agregadas. Espero un feedback

**Comment by amunozdev** [comment]
Buenísimo, ahora si quedo joya, a mi criterio hay algunas cositas que se podrían mejorar:

- Sección **Mis datos**:
Estaría muy bueno que me muestre mi data como usuario, en este caso mi nombre.

- Sección **Reportar mascota**:
El boton de para subir la imagen podria ser un poco mas intuitivo,
![Screenshot from 2022-08-30 17-43-03](https://user-images.githubusercontent.com/77214476/187543046-f15b9eee-dc7e-49af-83c8-d1046e506364.png)

Por ejemplo, con un icon para agregar una imagen como estos:
![Screenshot from 2022-08-30 18-06-46](https://user-images.githubusercontent.com/77214476/187543291-aacd87c4-f968-4655-9b91-70f832a5b8c0.png)

Ya que en un principio pensé que era un boton para setear el nombre de la mascota y me costó darme cuenta de que ese botón era para subir una imagen.

- Sección **Mis mascotas reportadas**:
El form para editar una mascota quedo algo desordenado y pienso que quedaría mejor y más limpio si los campos y los elementos del form estuvieran ordenados, es decir, primero el nombre de la mascota, luego la imagen y luego la ubicación:
![Screenshot from 2022-08-30 18-01-59](https://user-images.githubusercontent.com/77214476/187543886-da84b1b8-7a9c-4372-876a-5d15bd338759.png)

Estaría bueno tener una funcionalidad para despublicar/eliminar un reporte de una mascota perdida.

- **Menu**:
Lo veo súper, estaría bueno tener la opción para cerrar y abrir sesión desde el mismo, ya que sería más fácil que ir hasta la sección "Mis datos" para cerrar sesión.

- backend/Routes/endpoints.ts:
![Screenshot from 2022-08-30 18-25-48](https://user-images.githubusercontent.com/77214476/187546362-d69853f4-a02a-4b02-a081-585978698388.png)
Lo mejor en este caso es que el endpoint no maneje nada o lo menos posible de esa lógica, lo ideal es que esa lógica esté separada en un controller, la responsabilidad del endpoint debería ser la de recibir un request y mandar una respuesta.

- backend/controllers/pet-controller.ts:
![Screenshot from 2022-08-30 18-32-00](https://user-images.githubusercontent.com/77214476/187547263-c6854bf6-da3a-4a28-9576-c118c8e433b1.png)
Se dice que una buena práctica es que una función no reciba más de dos o tres parámetros como mucho, cuando se supera esa cantidad lo mejor es pasar un objeto con todas los parámetros, con esto quedaría un código más limpio y más fácil de tipar.

- frontend/libs:
Separar las llamadas a la api en un archivo aparte está excelente!!! además todo bien tipado 👌

En cuanto a las pages y componentes, no es necesario encerrar a las clases dentro de funciones, ya que después tenés que hacer todas las llamadas en el index, con solo importar la clase en el index, ya está disponible para usar la page o el component.

Después en general lo veo todo bastante bien, el Readme suma un monon y más allá de esos detalles que se podrían mejorar, el desafío cuenta con las condiciones para aprobar, éxitos en lo que sigue!!

**Comment by RichardIrala** [comment]
Las llamadas a cada elemento custom (instanciar_milanesa_page, etc etc) que llame en el index fue para evitar problemas al compilarse en JS porque los imports de cada módulo pueden llegar a causar problemas a futuro si activase el módulo con todo su contenido. Por eso tome la ruta de hacer cada instancia como si fueran métodos de una constante, me pareció mejor a futuro.

**Comment by RichardIrala** [comment]
Respecto a manejar las propiedades de los controllers a través de OBJETOS ya lo tengo planteado y voy a ir cambiando de vez en cuando cada controller para que reciba pocos parámetros y en lo posible objetos. Lo de modificar mascotas me sirve un montón lo voy a aplicar dentro de la semana de manera más prolija y voy a intentar que esa página sea super intuitiva. Mi idea es simplificar el código de este desafío como pasatiempo este mes mientras aprendo todo lo relacionado al módulo 8.
